# Generated by Django 2.2 on 2020-04-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Dest',
        ),
    ]
