# Generated by Django 2.2 on 2020-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0002_auto_20200429_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Dest',
        ),
    ]
